### ISSUE TITLE
FGMS Multiplay server does not compile using version 0.9.11

### ISSUE THREAD

**Issue by pedromorgan** [pedromorgan/flightgear-issues-test#72]
_From [angisang...@yahoo.com](https://code.google.com/u/101683260209624192770/) on February 13, 2010 18:39:54_

What steps will reproduce the problem? 1. Get the stable tarball at http://fgms.sourceforge.net/stableversion.php 2. untar
3. configure
4. make What is the expected output? What do you see instead? 'make' should run through the compile process. Instead it stops due to
multiple errors (e.g. "xxx was not declared in this scope") What version of the product are you using? On what operating system? Ubuntu 2.6.31.-20 Please provide any additional information below. Several includes have to be set to make the compile run successful. Hereby
I prove an attached patch file to make fgms working.

**Attachment:** [fgms-0.9.11-fgms-0.9.12.patch](http://code.google.com/p/flightgear-bugs/issues/detail?id=73)

_Original issue: http://code.google.com/p/flightgear-bugs/issues/detail?id=73_

**Comment by pedromorgan** [comment]
_From [pedromor...@gmail.com](https://code.google.com/u/112081649209717344658/) on February 13, 2010 10:43:41_

**Labels:** FGMS

**Comment by pedromorgan** [comment]
_From [pedromor...@gmail.com](https://code.google.com/u/112081649209717344658/) on February 13, 2010 10:52:49_

**Status:** Triaged  
**Labels:** Oliver

**Comment by pedromorgan** [comment]
_From [pedromor...@gmail.com](https://code.google.com/u/112081649209717344658/) on February 13, 2010 10:55:21_

After adding the above patch, get another error

/usr/bin/make  all-recursive
make[1]: Entering directory `/home/mash/Downloads/fgms-0.9.11'
Making all in src
make[2]: Entering directory `/home/mash/Downloads/fgms-0.9.11/src'
Making all in simgear
make[3]: Entering directory `/home/mash/Downloads/fgms-0.9.11/src/simgear'
Making all in debug
make[4]: Entering directory `/home/mash/Downloads/fgms-0.9.11/src/simgear/debug'
if g++ -DHAVE_CONFIG_H -I. -I. -I../../.. -I../../.. -I../../../src    -Wall -MT 
logstream.o -MD -MP -MF ".deps/logstream.Tpo" -c -o logstream.o logstream.cxx; \
        then mv -f ".deps/logstream.Tpo" ".deps/logstream.Po"; else rm -f 
".deps/logstream.Tpo"; exit 1; fi
In file included from logstream.cxx:23:
logstream.hxx: In member function ‘virtual int logbuf::overflow(int)’:
logstream.hxx:213: error: ‘EOF’ was not declared in this scope
logstream.cxx: In member function ‘std::string logstream::datestr()’:
logstream.cxx:111: error: ‘sprintf’ was not declared in this scope
make[4]: *** [logstream.o] Error 1

**Comment by pedromorgan** [comment]
_From [angisang...@yahoo.com](https://code.google.com/u/101683260209624192770/) on February 13, 2010 12:16:21_

It looks like the diff does not bring in all desired changes. Try to replace the
attached files manually.

**Attachment:** [fgms-0.9.11.mod-by-mike.tar.gz](http://code.google.com/p/flightgear-bugs/issues/detail?id=73#hc4)

**Comment by pedromorgan** [comment]
_From [pedromor...@gmail.com](https://code.google.com/u/112081649209717344658/) on February 13, 2010 12:29:48_

Compiles of with comment `#4` patch

**Comment by pedromorgan** [comment]
_From [angisang...@yahoo.com](https://code.google.com/u/101683260209624192770/) on February 15, 2010 22:52:35_

Change comitted, merged and published: http://fgms.sourceforge.net/index.php

**Comment by pedromorgan** [comment]
_From [pedromor...@gmail.com](https://code.google.com/u/112081649209717344658/) on February 16, 2010 08:32:19_

**Status:** Fixed

**Comment by pedromorgan** [comment]
_From [bre...@gmail.com](https://code.google.com/u/112567806978334989774/) on June 05, 2011 02:52:29_

**Status:** Temp

**Comment by pedromorgan** [comment]
_From [bre...@gmail.com](https://code.google.com/u/112567806978334989774/) on June 05, 2011 02:52:48_

**Status:** Fixed
